[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120

[tool.pylint]
max-line-length = 120

[tool.isort]
line_length = 120

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
